services:
    netgen_remote_media.controllers.ezadminui.folders.list:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\Folders\ListController
        arguments:
            - '@netgen_remote_media.provider'

    netgen_remote_media.controllers.ezadminui.browse:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\BrowseController
        arguments:
            - '@netgen_remote_media.provider'
            - '@netgen_remote_media.helper'

    netgen_remote_media.controllers.ezadminui.editorinsert:
        class: Netgen\Bundle\RemoteMediaBundle\Controller\EzAdminUI\EditorInsertController
        arguments:
            - '@netgen_remote_media.admin.field_update.helper'
            - '@netgen_remote_media.provider'
