imports:
    - { resource: 'ezadminui/controllers.yml' }

parameters:
    netgen_remote_media.remove_unused_resources: false
    netgen_remote_media.ezoe.class_list:
        - { name: 'Embed left', value: 'embed-left' }
        - { name: 'Embed right', value: 'embed-right' }

services:
    netgen_remote_media.handler_registry:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Transformation\Registry

    netgen_remote_media.variation.resolver:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\VariationResolver
        lazy: true
        arguments:
            - "@ezpublish.config.resolver"

    netgen_remote_media.provider.cloudinary.gateway:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\Gateway\CloudinaryApiGateway
        calls:
            - [initCloudinary, ['%netgen_remote_media.parameters.cloudinary.account_name%', '%netgen_remote_media.parameters.cloudinary.account_key%', "%netgen_remote_media.parameters.cloudinary.account_secret%", "%netgen_remote_media.parameters.use_subdomains%"]]
            - [setInternalLimit, ["%netgen_remote_media.cloudinary.internal_limit%"]]

    netgen_remote_media.provider.cloudinary:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Provider\Cloudinary\CloudinaryProvider
        arguments:
            - "@netgen_remote_media.handler_registry"
            - "@netgen_remote_media.variation.resolver"
            - "@netgen_remote_media.provider.cloudinary.gateway.cached"
            - "@?logger"

    netgen_remote_media.helper:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\Helper
        arguments:
            - "@netgen_remote_media.provider"

    # eZ Admin v2 support
    netgen_remote_media.ezadminui.component.javascripts:
        parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
        public: false
        arguments:
            - "@twig"
            - "@@NetgenRemoteMedia/ezadminui/javascripts.html.twig"
        tags:
            - { name: ezplatform.admin_ui.component, group: 'script-body' }

    netgen_remote_media.ezadminui.component.stylesheets:
        parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
        public: false
        arguments:
            - "@twig"
            - "@@NetgenRemoteMedia/ezadminui/stylesheets.html.twig"
        tags:
            - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }

    netgen_remote_media.next_cursor_resolver:
        class: Netgen\Bundle\RemoteMediaBundle\RemoteMedia\NextCursorResolver
        arguments:
            - "@ezpublish.cache_pool"
            - "%netgen_remote_media.cloudinary.cache_ttl%"
